# -*- coding: utf-8 -*-
"""edd_grafo4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-eTH_DUqzKxj6fRYOvn4yErnxxcaur36
"""

import networkx as nx
import matplotlib.pyplot as plt

grafo = nx.DiGraph()

grafo.add_nodes_from(['Prince','David Bowie','Michael Jackson','Beyoncé','Kanye West','Jay-Z','Rihanna','Madonna','Lady Gaga'])

grafo.add_edges_from([('David Bowie','Prince'),
                      ('David Bowie','Madonna'),
                      ('Prince','Michael Jackson'),
                      ('Madonna','Lady Gaga'),
                      ('Michael Jackson','Beyoncé'),
                      ('Beyoncé','Rihanna'),
                      ('Jay-Z','Kanye West'),
                      ('Jay-Z','Rihanna'),
                      ('Kanye West','Rihanna'),
                      ])

pos = nx.spring_layout(grafo, seed=42)

nx.draw (grafo, pos, with_labels = True, node_color = 'yellow', node_size = 600, font_weight='bold', font_size=10, arrowsize=15)

plt.title('Grafo de influência entre pessoas famosas')
plt.show()