# -*- coding: utf-8 -*-
"""edd_grafo3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KnzpKEfEh2Df0sQQYSKWqpr8Uo9-Fz8
"""

import networkx as nx
import matplotlib.pyplot as plt

grafo = nx.DiGraph()

grafo.add_nodes_from(['Elvis','Fã-1','Fã-2','Fã-3','Não-fã'])

grafo.add_edges_from([('Fã-1','Elvis'),
                      ('Fã-2','Elvis'),
                      ('Fã-3','Elvis')])

pos = nx.spring_layout(grafo, seed=42)

nx.draw(grafo, pos, with_labels = True, node_color ='purple', node_size = 2000, font_color='white', font_size =7, arrowsize=15)

plt.title('Representação em grafo direcionado')
plt.show()