# -*- coding: utf-8 -*-
"""edd_grafo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151qNeWzYMqZFENUGLeiUT2cmJCf4c8zy
"""

import networkx as nx
import matplotlib.pyplot as plt

grafo = nx.Graph()

grafo.add_nodes_from(['Audrey','Bill','Cathy','Dave','Emily','Frank','Gayle','Harry','Ilana','Jeff'])

grafo.add_edges_from([('Audrey','Bill'),
                      ('Audrey','Gayle'),
                      ('Audrey','Ilana'),
                      ('Bill','Gayle'),
                      ('Bill','Emily'),
                      ('Bill','Jeff'),
                      ('Cathy','Gayle'),
                      ('Cathy','Emily'),
                      ('Dave','Ilana'),
                      ('Dave','Emily'),
                      ('Dave','Frank'),
                      ('Emily','Jeff'),
                      ('Emily','Frank'),
                      ('Harry','Jeff'),
                      ('Harry','Ilana'),])

print(f"Nós do grafo: {grafo.nodes()}")
print(f"Arestas do grafo: {grafo.edges()}")
print(f"Contando o número de nós: {grafo.number_of_nodes()}")
print(f"Contando o número de arestas: {grafo.number_of_edges()}")

pos = nx.circular_layout(grafo, scale=1, center=None, dim=2, store_pos_as=None)

nx.draw(grafo, pos, with_labels = True, node_color='lightblue', font_weight = 'bold', node_size = 1000, font_size = 10)

plt.title('Olha o grafo aí')
plt.show()