# -*- coding: utf-8 -*-
"""edd_grafo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1LbdV5AomJG465wKqnyTM9b5OPHnkdO
"""

import networkx as nx
import matplotlib.pyplot as plt

#cria um grafo simples
G = nx.Graph()

#adiciona nós ao grafo
G.add_nodes_from(['João','Paulo','Maria','Joana','Antonia','Lili','Raimundo'])

#adiciona arestas
G.add_edges_from ([('João','Paulo'),
                   ('Paulo', 'Maria'),
                   ('Paulo', 'Joana'),
                   ('Paulo','Antonia'),
                   ('Paulo','Lili'),
                   ('Maria','Joana'),
                   ('Joana','Antonia'),
                   ('Antonia','Lili'),])

#imprime o grafo
print(f"Nós do grafo: {G.nodes()}")
print(f"Arestas do grafo: {G.edges()}")
print(f"Contando o número de nós: {G.number_of_nodes()}")
print(f"Contando o número de arestas: {G.number_of_edges()}")

pos = nx.spring_layout(G, seed=42)

nx.draw(G, pos, with_labels = True, node_color='lightblue', font_weight='bold', node_size=700, font_size=10)

plt.title('Representação em grafo simples')
plt.show()